import type { RuleDefinition, Severity, Strictness } from "./types.js";

const defineRule = (
  id: string,
  category: string,
  defaultSeverity: Severity,
  title: string,
  description: string,
  why: string,
  help: string,
  options: Partial<Pick<RuleDefinition, "pedanticSeverity" | "strictSeverity" | "weight">> = {},
): RuleDefinition => ({
  id,
  title,
  category,
  defaultSeverity,
  description,
  why,
  help,
  weight: options.weight ?? 1,
  strictSeverity: options.strictSeverity,
  pedanticSeverity: options.pedanticSeverity,
});

export const rules = {
  targetNotFound: defineRule(
    "skill.target-not-found",
    "structure",
    "error",
    "Missing target path",
    "The target path does not exist.",
    "The CLI can only analyze real directories or a concrete SKILL.md file.",
    "Pass an existing skill directory, a workspace that contains skills, or a direct path to SKILL.md.",
    { weight: 3 },
  ),
  targetNotDirectory: defineRule(
    "skill.target-not-directory",
    "structure",
    "error",
    "Target is not a directory",
    "The target path is not a directory or a SKILL.md file.",
    "Workspaces and skill roots are directory-scoped.",
    "Point the CLI at the skill root, the workspace root, or a specific SKILL.md file.",
    { weight: 3 },
  ),
  noSkillsFound: defineRule(
    "skill.no-skills-found",
    "structure",
    "error",
    "No skills found",
    "The target directory does not contain any SKILL.md files.",
    "Without a skill entrypoint there is nothing meaningful to analyze.",
    "Make sure the directory contains at least one skill package with SKILL.md at its root.",
    { weight: 3 },
  ),
  missingSkillMd: defineRule(
    "skill.missing-skill-md",
    "structure",
    "error",
    "Missing SKILL.md",
    "The skill root does not contain a SKILL.md file.",
    "SKILL.md is the contract surface for routing, documentation, and bundled resource references.",
    "Add a SKILL.md file to the skill root.",
    { weight: 3 },
  ),
  emptySkillMd: defineRule(
    "skill.empty-skill-md",
    "structure",
    "error",
    "Empty SKILL.md",
    "The SKILL.md file is empty.",
    "An empty skill cannot communicate trigger conditions, workflow, or bundled resources.",
    "Add frontmatter and a minimal body that explains the skill's trigger and workflow.",
    { weight: 3 },
  ),
  missingFrontmatter: defineRule(
    "skill.missing-frontmatter",
    "metadata",
    "error",
    "Missing frontmatter",
    "The skill does not start with YAML frontmatter.",
    "The spec relies on frontmatter for routing and discovery.",
    "Add a leading YAML block with at least `name` and `description`.",
    { weight: 3 },
  ),
  invalidFrontmatter: defineRule(
    "skill.invalid-frontmatter",
    "metadata",
    "error",
    "Invalid frontmatter",
    "The frontmatter could not be parsed as valid YAML.",
    "Broken metadata makes routing and linting unreliable.",
    "Fix the YAML syntax so the frontmatter parses cleanly.",
    { weight: 3 },
  ),
  unexpectedFrontmatterKey: defineRule(
    "skill.unexpected-frontmatter-key",
    "metadata",
    "warning",
    "Unexpected frontmatter key",
    "The frontmatter contains keys outside the commonly-supported skill surface.",
    "Unexpected keys often indicate typos, stale metadata, or assumptions tied to one ecosystem.",
    "Keep frontmatter focused on supported keys like `name`, `description`, `compatibility`, `allowed-tools`, `license`, and `metadata`.",
  ),
  missingFrontmatterName: defineRule(
    "skill.missing-frontmatter-name",
    "metadata",
    "error",
    "Missing skill name",
    "The frontmatter is missing the `name` field.",
    "The name is the skill's stable identifier in catalogs and evaluation tooling.",
    "Add a kebab-case `name` to the frontmatter.",
    { weight: 3 },
  ),
  invalidFrontmatterName: defineRule(
    "skill.invalid-frontmatter-name",
    "metadata",
    "error",
    "Invalid skill name",
    "The `name` field is present but invalid.",
    "Names that are not kebab-case or are too long are brittle for tooling and packaging.",
    "Use a concise kebab-case identifier with lowercase letters, digits, and single hyphens.",
    { weight: 3 },
  ),
  missingFrontmatterDescription: defineRule(
    "skill.missing-frontmatter-description",
    "metadata",
    "warning",
    "Missing skill description",
    "The frontmatter is missing the `description` field.",
    "Descriptions are the highest-leverage trigger signal for most skill systems.",
    "Add a description that says what the skill does and when it should trigger.",
    { strictSeverity: "error", pedanticSeverity: "error", weight: 2 },
  ),
  invalidFrontmatterDescription: defineRule(
    "skill.invalid-frontmatter-description",
    "metadata",
    "error",
    "Invalid skill description",
    "The `description` field is present but invalid.",
    "Descriptions that are malformed or spec-breaking can derail skill routing.",
    "Use a plain string description without angle brackets and keep it within the practical length limits.",
    { weight: 3 },
  ),
  shortFrontmatterDescription: defineRule(
    "skill.short-frontmatter-description",
    "metadata",
    "warning",
    "Short skill description",
    "The description is too short to clearly route the skill.",
    "Very short descriptions rarely explain both purpose and trigger conditions.",
    "Expand the description with the main job and the situations that should trigger the skill.",
    { strictSeverity: "error" },
  ),
  longFrontmatterDescription: defineRule(
    "skill.long-frontmatter-description",
    "metadata",
    "warning",
    "Long skill description",
    "The description is long enough to hide the trigger signal in metadata noise.",
    "Overly long descriptions are harder to scan in catalogs and can underperform as triggers.",
    "Keep the metadata compact and move detailed workflow guidance into the body or references.",
  ),
  descriptionMissingTriggerGuidance: defineRule(
    "skill.description-missing-trigger-guidance",
    "trigger-quality",
    "warning",
    "Weak trigger guidance",
    "The description does not clearly say when the skill should be used.",
    "A skill is easier to route when the description names concrete request patterns or trigger situations.",
    "Add phrases like `use when`, `trigger when`, `if the user asks`, or equivalent trigger language.",
    { strictSeverity: "error" },
  ),
  genericDescription: defineRule(
    "skill.generic-description",
    "trigger-quality",
    "warning",
    "Generic skill description",
    "The description reads as too generic to stand out from general assistant behavior.",
    "Generic descriptions make the skill harder to trigger intentionally.",
    "Replace vague wording with a distinct task, domain, or request pattern.",
  ),
  brokenLocalLink: defineRule(
    "skill.broken-local-link",
    "resources",
    "error",
    "Broken local link",
    "A local markdown link points to a file that does not exist.",
    "Broken links create dead ends right where the skill expects the agent to go next.",
    "Fix the relative path or remove the broken link.",
    { weight: 2 },
  ),
  referenceOutsideRoot: defineRule(
    "skill.reference-outside-root",
    "resources",
    "error",
    "Reference escapes the skill root",
    "A local reference resolves outside the skill package.",
    "References outside the bundle make the skill brittle and hard to share.",
    "Keep bundled references relative to the skill root.",
    { weight: 2 },
  ),
  referencedDirectory: defineRule(
    "skill.referenced-directory",
    "resources",
    "warning",
    "Referenced directory",
    "A local link points at a directory instead of a file.",
    "Directory links are often accidental and do not provide a concrete artifact to load.",
    "Link to a specific file or describe the directory contents more directly.",
  ),
  emptyReferencedResource: defineRule(
    "skill.empty-referenced-resource",
    "resources",
    "warning",
    "Empty referenced resource",
    "A referenced local resource exists but is empty.",
    "Empty helper files look accidental and give the agent nothing useful to load.",
    "Populate the file or remove the reference.",
  ),
  missingMentionedResource: defineRule(
    "skill.missing-mentioned-resource",
    "resources",
    "warning",
    "Missing mentioned resource",
    "The skill strongly mentions a bundled resource that is not present.",
    "Mentioned scripts and references should generally exist if the workflow depends on them.",
    "Create the missing resource or remove the mention from the instructions.",
  ),
  shortContent: defineRule(
    "skill.short-content",
    "content",
    "warning",
    "Very short content",
    "The body is so short that the skill may not be actionable.",
    "A tiny body usually cannot explain workflow, constraints, or supporting resources well.",
    "Add a bit more procedural guidance, not just metadata.",
  ),
  duplicateHeading: defineRule(
    "skill.duplicate-heading",
    "content",
    "warning",
    "Duplicate heading",
    "The document reuses the same heading text multiple times.",
    "Duplicate headings make long skills harder to navigate and maintain.",
    "Rename repeated headings so each section has a distinct role.",
  ),
  missingUsageGuidance: defineRule(
    "skill.missing-usage-guidance",
    "content",
    "warning",
    "Missing usage guidance",
    "The body does not obviously explain how the skill should be used once triggered.",
    "Good skills do more than trigger; they tell the agent what workflow to follow next.",
    "Add a quick start, workflow, process, or usage section in the body.",
    { strictSeverity: "error", pedanticSeverity: "error" },
  ),
  largeInlineSkill: defineRule(
    "skill.large-inline-skill",
    "content",
    "warning",
    "Large inline skill",
    "The skill is large but does not appear to lean on references or scripts for progressive disclosure.",
    "Very large SKILL.md files are expensive to load and harder to evolve safely.",
    "Move detailed reference material or deterministic logic into `references/` or `scripts/` and keep SKILL.md focused.",
  ),
  invalidEvalsJson: defineRule(
    "evals.invalid-json",
    "evals",
    "error",
    "Invalid evals JSON",
    "The `evals/evals.json` file could not be parsed.",
    "Broken eval definitions make static validation and future benchmarking unreliable.",
    "Fix the JSON syntax in `evals/evals.json`.",
    { weight: 2 },
  ),
  invalidEvalsSchema: defineRule(
    "evals.invalid-schema",
    "evals",
    "error",
    "Invalid evals schema",
    "The `evals/evals.json` file does not match the expected top-level shape.",
    "Schema drift makes eval automation and viewers harder to trust.",
    "Use an object with `skill_name` and an `evals` array.",
    { weight: 2 },
  ),
  evalsSkillNameMismatch: defineRule(
    "evals.skill-name-mismatch",
    "evals",
    "warning",
    "Evals skill name mismatch",
    "The evals file points at a different skill name than the frontmatter.",
    "Mismatched skill names can silently benchmark the wrong package or stale copies.",
    "Keep `evals.skill_name` aligned with the SKILL.md `name`.",
    { strictSeverity: "error" },
  ),
  duplicateEvalId: defineRule(
    "evals.duplicate-id",
    "evals",
    "error",
    "Duplicate eval id",
    "Two evals share the same `id`.",
    "Duplicate IDs make results hard to compare across iterations and viewers.",
    "Give each eval a unique integer `id`.",
    { weight: 2 },
  ),
  emptyEvalPrompt: defineRule(
    "evals.empty-prompt",
    "evals",
    "error",
    "Empty eval prompt",
    "An eval entry is missing a usable `prompt`.",
    "Without a prompt the eval cannot represent a real task.",
    "Add a non-empty prompt string for each eval.",
    { weight: 2 },
  ),
  missingEvalFile: defineRule(
    "evals.missing-file",
    "evals",
    "error",
    "Missing eval file",
    "An eval references an input file that does not exist.",
    "Broken input files make evals fail before they test anything meaningful.",
    "Fix the relative path or add the missing file under the skill package.",
    { weight: 2 },
  ),
  missingExpectedOutput: defineRule(
    "evals.missing-expected-output",
    "evals",
    "warning",
    "Missing expected output",
    "An eval does not describe the expected result.",
    "Expected output text helps reviewers understand what success should look like.",
    "Add a concise `expected_output` description for each eval.",
  ),
  invalidEvalExpectations: defineRule(
    "evals.invalid-expectations",
    "evals",
    "warning",
    "Invalid expectations",
    "The eval expectations/assertions field is present but not a list of strings.",
    "Non-uniform expectation data is harder to review, grade, and benchmark.",
    "Use `expectations` or `assertions` as an array of plain strings.",
  ),
} satisfies Record<string, RuleDefinition>;

export const allRules = Object.values(rules);

export const findRule = (ruleId: string): RuleDefinition | undefined =>
  allRules.find((rule) => rule.id === ruleId);

export const severityForRule = (rule: RuleDefinition, strictness: Strictness): Severity => {
  if (strictness === "pedantic") {
    return rule.pedanticSeverity ?? rule.strictSeverity ?? rule.defaultSeverity;
  }

  if (strictness === "strict") {
    return rule.strictSeverity ?? rule.defaultSeverity;
  }

  return rule.defaultSeverity;
};
